(function(){this.canvg=function(l,d,e){if(l==null&&d==null&&e==null){var g=document.querySelectorAll("svg");
for(var j=0;
j<g.length;
j++){var h=g[j];
var m=document.createElement("canvas");
m.width=h.clientWidth;
m.height=h.clientHeight;
h.parentNode.insertBefore(m,h);
h.parentNode.removeChild(h);
var f=document.createElement("div");
f.appendChild(h);
canvg(m,f.innerHTML);
}return;
}if(typeof l=="string"){l=document.getElementById(l);
}if(l.svg!=null){l.svg.stop();
}var k=a(e||{});
if(!(l.childNodes.length==1&&l.childNodes[0].nodeName=="OBJECT")){l.svg=k;
}var b=l.getContext("2d");
if(typeof(d.documentElement)!="undefined"){k.loadXmlDoc(b,d);
}else{if(d.substr(0,1)=="<"){k.loadXml(b,d);
}else{k.load(b,d);
}}};
function a(d){var c={opts:d};
c.FRAMERATE=30;
c.MAX_VIRTUAL_PIXELS=30000;
c.log=function(e){};
if(c.opts["log"]==true&&typeof(console)!="undefined"){c.log=function(e){console.log(e);
};
}c.init=function(e){var f=0;
c.UniqueId=function(){f++;
return"canvg"+f;
};
c.Definitions={};
c.Styles={};
c.Animations=[];
c.Images=[];
c.ctx=e;
c.ViewPort=new (function(){this.viewPorts=[];
this.Clear=function(){this.viewPorts=[];
};
this.SetCurrent=function(h,g){this.viewPorts.push({width:h,height:g});
};
this.RemoveCurrent=function(){this.viewPorts.pop();
};
this.Current=function(){return this.viewPorts[this.viewPorts.length-1];
};
this.width=function(){return this.Current().width;
};
this.height=function(){return this.Current().height;
};
this.ComputeSize=function(g){if(g!=null&&typeof(g)=="number"){return g;
}if(g=="x"){return this.width();
}if(g=="y"){return this.height();
}return Math.sqrt(Math.pow(this.width(),2)+Math.pow(this.height(),2))/Math.sqrt(2);
};
});
};
c.init();
c.ImagesLoaded=function(){for(var e=0;
e<c.Images.length;
e++){if(!c.Images[e].loaded){return false;
}}return true;
};
c.trim=function(e){return e.replace(/^\s+|\s+$/g,"");
};
c.compressSpaces=function(e){return e.replace(/[\s\r\t\n]+/gm," ");
};
c.ajax=function(f){var e;
if(window.XMLHttpRequest){e=new XMLHttpRequest();
}else{e=new ActiveXObject("Microsoft.XMLHTTP");
}if(e){e.open("GET",f,false);
e.send(null);
return e.responseText;
}return null;
};
c.parseXml=function(e){if(window.DOMParser){var g=new DOMParser();
return g.parseFromString(e,"text/xml");
}else{e=e.replace(/<!DOCTYPE svg[^>]*>/,"");
var f=new ActiveXObject("Microsoft.XMLDOM");
f.async="false";
f.loadXML(e);
return f;
}};
c.Property=function(e,f){this.name=e;
this.value=f;
};
c.Property.prototype.getValue=function(){return this.value;
};
c.Property.prototype.hasValue=function(){return(this.value!=null&&this.value!=="");
};
c.Property.prototype.numValue=function(){if(!this.hasValue()){return 0;
}var e=parseFloat(this.value);
if((this.value+"").match(/%$/)){e=e/100;
}return e;
};
c.Property.prototype.valueOrDefault=function(e){if(this.hasValue()){return this.value;
}return e;
};
c.Property.prototype.numValueOrDefault=function(e){if(this.hasValue()){return this.numValue();
}return e;
};
c.Property.prototype.addOpacity=function(g){var f=this.value;
if(g.value!=null&&g.value!=""&&typeof(this.value)=="string"){var e=new RGBColor(this.value);
if(e.ok){f="rgba("+e.r+", "+e.g+", "+e.b+", "+g.numValue()+")";
}}return new c.Property(this.name,f);
};
c.Property.prototype.getDefinition=function(){var e=this.value.match(/#([^\)'"]+)/);
if(e){e=e[1];
}if(!e){e=this.value;
}return c.Definitions[e];
};
c.Property.prototype.isUrlDefinition=function(){return this.value.indexOf("url(")==0;
};
c.Property.prototype.getFillStyleDefinition=function(h,g){var e=this.getDefinition();
if(e!=null&&e.createGradient){return e.createGradient(c.ctx,h,g);
}if(e!=null&&e.createPattern){if(e.getHrefAttribute().hasValue()){var f=e.attribute("patternTransform");
e=e.getHrefAttribute().getDefinition();
if(f.hasValue()){e.attribute("patternTransform",true).value=f.value;
}}return e.createPattern(c.ctx,h);
}return null;
};
c.Property.prototype.getDPI=function(e){return 96;
};
c.Property.prototype.getEM=function(g){var e=12;
var f=new c.Property("fontSize",c.Font.Parse(c.ctx.font).fontSize);
if(f.hasValue()){e=f.toPixels(g);
}return e;
};
c.Property.prototype.getUnits=function(){var e=this.value+"";
return e.replace(/[0-9\.\-]/g,"");
};
c.Property.prototype.toPixels=function(g,e){if(!this.hasValue()){return 0;
}var f=this.value+"";
if(f.match(/em$/)){return this.numValue()*this.getEM(g);
}if(f.match(/ex$/)){return this.numValue()*this.getEM(g)/2;
}if(f.match(/px$/)){return this.numValue();
}if(f.match(/pt$/)){return this.numValue()*this.getDPI(g)*(1/72);
}if(f.match(/pc$/)){return this.numValue()*15;
}if(f.match(/cm$/)){return this.numValue()*this.getDPI(g)/2.54;
}if(f.match(/mm$/)){return this.numValue()*this.getDPI(g)/25.4;
}if(f.match(/in$/)){return this.numValue()*this.getDPI(g);
}if(f.match(/%$/)){return this.numValue()*c.ViewPort.ComputeSize(g);
}var h=this.numValue();
if(e&&h<1){return h*c.ViewPort.ComputeSize(g);
}return h;
};
c.Property.prototype.toMilliseconds=function(){if(!this.hasValue()){return 0;
}var e=this.value+"";
if(e.match(/s$/)){return this.numValue()*1000;
}if(e.match(/ms$/)){return this.numValue();
}return this.numValue();
};
c.Property.prototype.toRadians=function(){if(!this.hasValue()){return 0;
}var e=this.value+"";
if(e.match(/deg$/)){return this.numValue()*(Math.PI/180);
}if(e.match(/grad$/)){return this.numValue()*(Math.PI/200);
}if(e.match(/rad$/)){return this.numValue();
}return this.numValue()*(Math.PI/180);
};
var b={"baseline":"alphabetic","before-edge":"top","text-before-edge":"top","middle":"middle","central":"middle","after-edge":"bottom","text-after-edge":"bottom","ideographic":"ideographic","alphabetic":"alphabetic","hanging":"hanging","mathematical":"alphabetic"};
c.Property.prototype.toTextBaseline=function(){if(!this.hasValue()){return null;
}return b[this.value];
};
c.Font=new (function(){this.Styles="normal|italic|oblique|inherit";
this.Variants="normal|small-caps|inherit";
this.Weights="normal|bold|bolder|lighter|100|200|300|400|500|600|700|800|900|inherit";
this.CreateFont=function(f,l,h,m,g,j){var k=j!=null?this.Parse(j):this.CreateFont("","","","","",c.ctx.font);
return{fontFamily:g||k.fontFamily,fontSize:m||k.fontSize,fontStyle:f||k.fontStyle,fontWeight:h||k.fontWeight,fontVariant:l||k.fontVariant,toString:function(){return[this.fontStyle,this.fontVariant,this.fontWeight,this.fontSize,this.fontFamily].join(" ");
}};
};
var e=this;
this.Parse=function(k){var f={};
var g=c.trim(c.compressSpaces(k||"")).split(" ");
var h={fontSize:false,fontStyle:false,fontWeight:false,fontVariant:false};
var j="";
for(var l=0;
l<g.length;
l++){if(!h.fontStyle&&e.Styles.indexOf(g[l])!=-1){if(g[l]!="inherit"){f.fontStyle=g[l];
}h.fontStyle=true;
}else{if(!h.fontVariant&&e.Variants.indexOf(g[l])!=-1){if(g[l]!="inherit"){f.fontVariant=g[l];
}h.fontStyle=h.fontVariant=true;
}else{if(!h.fontWeight&&e.Weights.indexOf(g[l])!=-1){if(g[l]!="inherit"){f.fontWeight=g[l];
}h.fontStyle=h.fontVariant=h.fontWeight=true;
}else{if(!h.fontSize){if(g[l]!="inherit"){f.fontSize=g[l].split("/")[0];
}h.fontStyle=h.fontVariant=h.fontWeight=h.fontSize=true;
}else{if(g[l]!="inherit"){j+=g[l];
}}}}}}if(j!=""){f.fontFamily=j;
}return f;
};
});
c.ToNumberArray=function(g){var e=c.trim(c.compressSpaces((g||"").replace(/,/g," "))).split(" ");
for(var f=0;
f<e.length;
f++){e[f]=parseFloat(e[f]);
}return e;
};
c.Point=function(e,f){this.x=e;
this.y=f;
};
c.Point.prototype.angleTo=function(e){return Math.atan2(e.y-this.y,e.x-this.x);
};
c.Point.prototype.applyTransform=function(e){var f=this.x*e[0]+this.y*e[2]+e[4];
var g=this.x*e[1]+this.y*e[3]+e[5];
this.x=f;
this.y=g;
};
c.CreatePoint=function(f){var e=c.ToNumberArray(f);
return new c.Point(e[0],e[1]);
};
c.CreatePath=function(g){var e=c.ToNumberArray(g);
var h=[];
for(var f=0;
f<e.length;
f+=2){h.push(new c.Point(e[f],e[f+1]));
}return h;
};
c.BoundingBox=function(f,h,e,g){this.x1=Number.NaN;
this.y1=Number.NaN;
this.x2=Number.NaN;
this.y2=Number.NaN;
this.x=function(){return this.x1;
};
this.y=function(){return this.y1;
};
this.width=function(){return this.x2-this.x1;
};
this.height=function(){return this.y2-this.y1;
};
this.addPoint=function(j,k){if(j!=null){if(isNaN(this.x1)||isNaN(this.x2)){this.x1=j;
this.x2=j;
}if(j<this.x1){this.x1=j;
}if(j>this.x2){this.x2=j;
}}if(k!=null){if(isNaN(this.y1)||isNaN(this.y2)){this.y1=k;
this.y2=k;
}if(k<this.y1){this.y1=k;
}if(k>this.y2){this.y2=k;
}}};
this.addX=function(j){this.addPoint(j,null);
};
this.addY=function(j){this.addPoint(null,j);
};
this.addBoundingBox=function(j){this.addPoint(j.x1,j.y1);
this.addPoint(j.x2,j.y2);
};
this.addQuadraticCurve=function(o,n,k,p,q,j){var s=o+2/3*(k-o);
var l=n+2/3*(p-n);
var m=s+1/3*(q-o);
var r=l+1/3*(j-n);
this.addBezierCurve(o,n,s,m,l,r,q,j);
};
this.addBezierCurve=function(v,C,n,l,r,z,u,A){var o=[v,C],m=[n,l],k=[r,z],j=[u,A];
this.addPoint(o[0],o[1]);
this.addPoint(j[0],j[1]);
for(i=0;
i<=1;
i++){var p=function(t){return Math.pow(1-t,3)*o[i]+3*Math.pow(1-t,2)*t*m[i]+3*(1-t)*Math.pow(t,2)*k[i]+Math.pow(t,3)*j[i];
};
var D=6*o[i]-12*m[i]+6*k[i];
var y=-3*o[i]+9*m[i]-9*k[i]+3*j[i];
var B=3*m[i]-3*o[i];
if(y==0){if(D==0){continue;
}var w=-B/D;
if(0<w&&w<1){if(i==0){this.addX(p(w));
}if(i==1){this.addY(p(w));
}}continue;
}var s=Math.pow(D,2)-4*B*y;
if(s<0){continue;
}var x=(-D+Math.sqrt(s))/(2*y);
if(0<x&&x<1){if(i==0){this.addX(p(x));
}if(i==1){this.addY(p(x));
}}var q=(-D-Math.sqrt(s))/(2*y);
if(0<q&&q<1){if(i==0){this.addX(p(q));
}if(i==1){this.addY(p(q));
}}}};
this.isPointInBox=function(j,k){return(this.x1<=j&&j<=this.x2&&this.y1<=k&&k<=this.y2);
};
this.addPoint(f,h);
this.addPoint(e,g);
};
c.Transform=function(g){var e=this;
this.Type={};
this.Type.translate=function(m){this.p=c.CreatePoint(m);
this.apply=function(n){n.translate(this.p.x||0,this.p.y||0);
};
this.unapply=function(n){n.translate(-1*this.p.x||0,-1*this.p.y||0);
};
this.applyToPoint=function(n){n.applyTransform([1,0,0,1,this.p.x||0,this.p.y||0]);
};
};
this.Type.rotate=function(n){var m=c.ToNumberArray(n);
this.angle=new c.Property("angle",m[0]);
this.cx=m[1]||0;
this.cy=m[2]||0;
this.apply=function(o){o.translate(this.cx,this.cy);
o.rotate(this.angle.toRadians());
o.translate(-this.cx,-this.cy);
};
this.unapply=function(o){o.translate(this.cx,this.cy);
o.rotate(-1*this.angle.toRadians());
o.translate(-this.cx,-this.cy);
};
this.applyToPoint=function(p){var o=this.angle.toRadians();
p.applyTransform([1,0,0,1,this.p.x||0,this.p.y||0]);
p.applyTransform([Math.cos(o),Math.sin(o),-Math.sin(o),Math.cos(o),0,0]);
p.applyTransform([1,0,0,1,-this.p.x||0,-this.p.y||0]);
};
};
this.Type.scale=function(m){this.p=c.CreatePoint(m);
this.apply=function(n){n.scale(this.p.x||1,this.p.y||this.p.x||1);
};
this.unapply=function(n){n.scale(1/this.p.x||1,1/this.p.y||this.p.x||1);
};
this.applyToPoint=function(n){n.applyTransform([this.p.x||0,0,0,this.p.y||0,0,0]);
};
};
this.Type.matrix=function(m){this.m=c.ToNumberArray(m);
this.apply=function(n){n.transform(this.m[0],this.m[1],this.m[2],this.m[3],this.m[4],this.m[5]);
};
this.unapply=function(n){n.transform(this.m[0],this.m[1],this.m[2],this.m[3],-1*this.m[4],-1*this.m[5]);
};
this.applyToPoint=function(n){n.applyTransform(this.m);
};
};
this.Type.SkewBase=function(m){this.base=e.Type.matrix;
this.base(m);
this.angle=new c.Property("angle",m);
};
this.Type.SkewBase.prototype=new this.Type.matrix;
this.Type.skewX=function(m){this.base=e.Type.SkewBase;
this.base(m);
this.m=[1,0,Math.tan(this.angle.toRadians()),1,0,0];
};
this.Type.skewX.prototype=new this.Type.SkewBase;
this.Type.skewY=function(m){this.base=e.Type.SkewBase;
this.base(m);
this.m=[1,Math.tan(this.angle.toRadians()),0,1,0,0];
};
this.Type.skewY.prototype=new this.Type.SkewBase;
this.transforms=[];
this.apply=function(m){for(var n=0;
n<this.transforms.length;
n++){this.transforms[n].apply(m);
}};
this.unapply=function(m){for(var n=this.transforms.length-1;
n>=0;
n--){this.transforms[n].unapply(m);
}};
this.applyToPoint=function(n){for(var m=0;
m<this.transforms.length;
m++){this.transforms[m].applyToPoint(n);
}};
var l=c.trim(c.compressSpaces(g)).replace(/\)([a-zA-Z])/g,") $1").replace(/\)(\s?,\s?)/g,") ").split(/\s(?=[a-z])/);
for(var k=0;
k<l.length;
k++){var f=c.trim(l[k].split("(")[0]);
var j=l[k].split("(")[1].replace(")","");
var h=new this.Type[f](j);
h.type=f;
this.transforms.push(h);
}};
c.AspectRatio=function(f,u,h,m,l,t,g,k,s,j){u=c.compressSpaces(u);
u=u.replace(/^defer\s/,"");
var p=u.split(" ")[0]||"xMidYMid";
var e=u.split(" ")[1]||"meet";
var r=h/m;
var q=l/t;
var o=Math.min(r,q);
var n=Math.max(r,q);
if(e=="meet"){m*=o;
t*=o;
}if(e=="slice"){m*=n;
t*=n;
}s=new c.Property("refX",s);
j=new c.Property("refY",j);
if(s.hasValue()&&j.hasValue()){f.translate(-o*s.toPixels("x"),-o*j.toPixels("y"));
}else{if(p.match(/^xMid/)&&((e=="meet"&&o==q)||(e=="slice"&&n==q))){f.translate(h/2-m/2,0);
}if(p.match(/YMid$/)&&((e=="meet"&&o==r)||(e=="slice"&&n==r))){f.translate(0,l/2-t/2);
}if(p.match(/^xMax/)&&((e=="meet"&&o==q)||(e=="slice"&&n==q))){f.translate(h-m,0);
}if(p.match(/YMax$/)&&((e=="meet"&&o==r)||(e=="slice"&&n==r))){f.translate(0,l-t);
}}if(p=="none"){f.scale(r,q);
}else{if(e=="meet"){f.scale(o,o);
}else{if(e=="slice"){f.scale(n,n);
}}}f.translate(g==null?0:-g,k==null?0:-k);
};
c.Element={};
c.EmptyProperty=new c.Property("EMPTY","");
c.Element.ElementBase=function(m){this.attributes={};
this.styles={};
this.children=[];
this.attribute=function(r,s){var j=this.attributes[r];
if(j!=null){return j;
}if(s==true){j=new c.Property(r,"");
this.attributes[r]=j;
}return j||c.EmptyProperty;
};
this.getHrefAttribute=function(){for(var j in this.attributes){if(j.match(/:href$/)){return this.attributes[j];
}}return c.EmptyProperty;
};
this.style=function(j,r,v){var w=this.styles[j];
if(w!=null){return w;
}var t=this.attribute(j);
if(t!=null&&t.hasValue()){this.styles[j]=t;
return t;
}if(v!=true){var u=this.parent;
if(u!=null){var s=u.style(j);
if(s!=null&&s.hasValue()){return s;
}}}if(r==true){w=new c.Property(j,"");
this.styles[j]=w;
}return w||c.EmptyProperty;
};
this.render=function(r){if(this.style("display").value=="none"){return;
}if(this.style("visibility").value=="hidden"){return;
}r.save();
if(this.attribute("mask").hasValue()){var j=this.attribute("mask").getDefinition();
if(j!=null){j.apply(r,this);
}}else{if(this.style("filter").hasValue()){var s=this.style("filter").getDefinition();
if(s!=null){s.apply(r,this);
}}else{this.setContext(r);
this.renderChildren(r);
this.clearContext(r);
}}r.restore();
};
this.setContext=function(j){};
this.clearContext=function(j){};
this.renderChildren=function(j){for(var r=0;
r<this.children.length;
r++){this.children[r].render(j);
}};
this.addChild=function(r,j){var s=r;
if(j){s=c.CreateElement(r);
}s.parent=this;
if(s.type!="title"){this.children.push(s);
}};
if(m!=null&&m.nodeType==1){for(var p=0;
p<m.childNodes.length;
p++){var g=m.childNodes[p];
if(g.nodeType==1){this.addChild(g,true);
}if(this.captureTextNodes&&(g.nodeType==3||g.nodeType==4)){var e=g.nodeValue||g.text||"";
if(c.trim(c.compressSpaces(e))!=""){this.addChild(new c.Element.tspan(g),false);
}}}for(var p=0;
p<m.attributes.length;
p++){var l=m.attributes[p];
this.attributes[l.nodeName]=new c.Property(l.nodeName,l.nodeValue);
}var f=c.Styles[m.nodeName];
if(f!=null){for(var k in f){this.styles[k]=f[k];
}}if(this.attribute("class").hasValue()){var n=c.compressSpaces(this.attribute("class").value).split(" ");
for(var o=0;
o<n.length;
o++){f=c.Styles["."+n[o]];
if(f!=null){for(var k in f){this.styles[k]=f[k];
}}f=c.Styles[m.nodeName+"."+n[o]];
if(f!=null){for(var k in f){this.styles[k]=f[k];
}}}}if(this.attribute("id").hasValue()){var f=c.Styles["#"+this.attribute("id").value];
if(f!=null){for(var k in f){this.styles[k]=f[k];
}}}if(this.attribute("style").hasValue()){var f=this.attribute("style").value.split(";");
for(var p=0;
p<f.length;
p++){if(c.trim(f[p])!=""){var h=f[p].split(":");
var k=c.trim(h[0]);
var q=c.trim(h[1]);
this.styles[k]=new c.Property(k,q);
}}}if(this.attribute("id").hasValue()){if(c.Definitions[this.attribute("id").value]==null){c.Definitions[this.attribute("id").value]=this;
}}}};
c.Element.RenderedElementBase=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.setContext=function(l){if(this.style("fill").isUrlDefinition()){var h=this.style("fill").getFillStyleDefinition(this,this.style("fill-opacity"));
if(h!=null){l.fillStyle=h;
}}else{if(this.style("fill").hasValue()){var k=this.style("fill");
if(k.value=="currentColor"){k.value=this.style("color").value;
}l.fillStyle=(k.value=="none"?"rgba(0,0,0,0)":k.value);
}}if(this.style("fill-opacity").hasValue()){var k=new c.Property("fill",l.fillStyle);
k=k.addOpacity(this.style("fill-opacity"));
l.fillStyle=k.value;
}if(this.style("stroke").isUrlDefinition()){var h=this.style("stroke").getFillStyleDefinition(this,this.style("stroke-opacity"));
if(h!=null){l.strokeStyle=h;
}}else{if(this.style("stroke").hasValue()){var j=this.style("stroke");
if(j.value=="currentColor"){j.value=this.style("color").value;
}l.strokeStyle=(j.value=="none"?"rgba(0,0,0,0)":j.value);
}}if(this.style("stroke-opacity").hasValue()){var j=new c.Property("stroke",l.strokeStyle);
j=j.addOpacity(this.style("stroke-opacity"));
l.strokeStyle=j.value;
}if(this.style("stroke-width").hasValue()){var g=this.style("stroke-width").toPixels();
l.lineWidth=g==0?0.001:g;
}if(this.style("stroke-linecap").hasValue()){l.lineCap=this.style("stroke-linecap").value;
}if(this.style("stroke-linejoin").hasValue()){l.lineJoin=this.style("stroke-linejoin").value;
}if(this.style("stroke-miterlimit").hasValue()){l.miterLimit=this.style("stroke-miterlimit").value;
}if(this.style("stroke-dasharray").hasValue()&&this.style("stroke-dasharray").value!="none"){var o=c.ToNumberArray(this.style("stroke-dasharray").value);
if(typeof(l.setLineDash)!="undefined"){l.setLineDash(o);
}else{if(typeof(l.webkitLineDash)!="undefined"){l.webkitLineDash=o;
}else{if(typeof(l.mozDash)!="undefined"&&!(o.length==1&&o[0]==0)){l.mozDash=o;
}}}var f=this.style("stroke-dashoffset").numValueOrDefault(1);
if(typeof(l.lineDashOffset)!="undefined"){l.lineDashOffset=f;
}else{if(typeof(l.webkitLineDashOffset)!="undefined"){l.webkitLineDashOffset=f;
}else{if(typeof(l.mozDashOffset)!="undefined"){l.mozDashOffset=f;
}}}}if(typeof(l.font)!="undefined"){l.font=c.Font.CreateFont(this.style("font-style").value,this.style("font-variant").value,this.style("font-weight").value,this.style("font-size").hasValue()?this.style("font-size").toPixels()+"px":"",this.style("font-family").value).toString();
}if(this.attribute("transform").hasValue()){var m=new c.Transform(this.attribute("transform").value);
m.apply(l);
}if(this.style("clip-path",false,true).hasValue()){var n=this.style("clip-path",false,true).getDefinition();
if(n!=null){n.apply(l);
}}if(this.style("opacity").hasValue()){l.globalAlpha=this.style("opacity").numValue();
}};
};
c.Element.RenderedElementBase.prototype=new c.Element.ElementBase;
c.Element.PathElementBase=function(e){this.base=c.Element.RenderedElementBase;
this.base(e);
this.path=function(f){if(f!=null){f.beginPath();
}return new c.BoundingBox();
};
this.renderChildren=function(g){this.path(g);
c.Mouse.checkPath(this,g);
if(g.fillStyle!=""){if(this.style("fill-rule").valueOrDefault("inherit")!="inherit"){g.fill(this.style("fill-rule").value);
}else{g.fill();
}}if(g.strokeStyle!=""){g.stroke();
}var j=this.getMarkers();
if(j!=null){if(this.style("marker-start").isUrlDefinition()){var f=this.style("marker-start").getDefinition();
f.render(g,j[0][0],j[0][1]);
}if(this.style("marker-mid").isUrlDefinition()){var f=this.style("marker-mid").getDefinition();
for(var h=1;
h<j.length-1;
h++){f.render(g,j[h][0],j[h][1]);
}}if(this.style("marker-end").isUrlDefinition()){var f=this.style("marker-end").getDefinition();
f.render(g,j[j.length-1][0],j[j.length-1][1]);
}}};
this.getBoundingBox=function(){return this.path();
};
this.getMarkers=function(){return null;
};
};
c.Element.PathElementBase.prototype=new c.Element.RenderedElementBase;
c.Element.svg=function(e){this.base=c.Element.RenderedElementBase;
this.base(e);
this.baseClearContext=this.clearContext;
this.clearContext=function(f){this.baseClearContext(f);
c.ViewPort.RemoveCurrent();
};
this.baseSetContext=this.setContext;
this.setContext=function(h){h.strokeStyle="rgba(0,0,0,0)";
h.lineCap="butt";
h.lineJoin="miter";
h.miterLimit=4;
if(typeof(h.font)!="undefined"&&typeof(window.getComputedStyle)!="undefined"){h.font=window.getComputedStyle(h.canvas).getPropertyValue("font");
}this.baseSetContext(h);
if(!this.attribute("x").hasValue()){this.attribute("x",true).value=0;
}if(!this.attribute("y").hasValue()){this.attribute("y",true).value=0;
}h.translate(this.attribute("x").toPixels("x"),this.attribute("y").toPixels("y"));
var j=c.ViewPort.width();
var g=c.ViewPort.height();
if(!this.attribute("width").hasValue()){this.attribute("width",true).value="100%";
}if(!this.attribute("height").hasValue()){this.attribute("height",true).value="100%";
}if(typeof(this.root)=="undefined"){j=this.attribute("width").toPixels("x");
g=this.attribute("height").toPixels("y");
var f=0;
var l=0;
if(this.attribute("refX").hasValue()&&this.attribute("refY").hasValue()){f=-this.attribute("refX").toPixels("x");
l=-this.attribute("refY").toPixels("y");
}if(this.attribute("overflow").valueOrDefault("hidden")!="visible"){h.beginPath();
h.moveTo(f,l);
h.lineTo(j,l);
h.lineTo(j,g);
h.lineTo(f,g);
h.closePath();
h.clip();
}}c.ViewPort.SetCurrent(j,g);
if(this.attribute("viewBox").hasValue()){var k=c.ToNumberArray(this.attribute("viewBox").value);
var n=k[0];
var m=k[1];
j=k[2];
g=k[3];
c.AspectRatio(h,this.attribute("preserveAspectRatio").value,c.ViewPort.width(),j,c.ViewPort.height(),g,n,m,this.attribute("refX").value,this.attribute("refY").value);
c.ViewPort.RemoveCurrent();
c.ViewPort.SetCurrent(k[2],k[3]);
}};
};
c.Element.svg.prototype=new c.Element.RenderedElementBase;
c.Element.rect=function(e){this.base=c.Element.PathElementBase;
this.base(e);
this.path=function(h){var g=this.attribute("x").toPixels("x");
var m=this.attribute("y").toPixels("y");
var j=this.attribute("width").toPixels("x");
var f=this.attribute("height").toPixels("y");
var l=this.attribute("rx").toPixels("x");
var k=this.attribute("ry").toPixels("y");
if(this.attribute("rx").hasValue()&&!this.attribute("ry").hasValue()){k=l;
}if(this.attribute("ry").hasValue()&&!this.attribute("rx").hasValue()){l=k;
}l=Math.min(l,j/2);
k=Math.min(k,f/2);
if(h!=null){h.beginPath();
h.moveTo(g+l,m);
h.lineTo(g+j-l,m);
h.quadraticCurveTo(g+j,m,g+j,m+k);
h.lineTo(g+j,m+f-k);
h.quadraticCurveTo(g+j,m+f,g+j-l,m+f);
h.lineTo(g+l,m+f);
h.quadraticCurveTo(g,m+f,g,m+f-k);
h.lineTo(g,m+k);
h.quadraticCurveTo(g,m,g+l,m);
h.closePath();
}return new c.BoundingBox(g,m,g+j,m+f);
};
};
c.Element.rect.prototype=new c.Element.PathElementBase;
c.Element.circle=function(e){this.base=c.Element.PathElementBase;
this.base(e);
this.path=function(g){var f=this.attribute("cx").toPixels("x");
var j=this.attribute("cy").toPixels("y");
var h=this.attribute("r").toPixels();
if(g!=null){g.beginPath();
g.arc(f,j,h,0,Math.PI*2,true);
g.closePath();
}return new c.BoundingBox(f-h,j-h,f+h,j+h);
};
};
c.Element.circle.prototype=new c.Element.PathElementBase;
c.Element.ellipse=function(e){this.base=c.Element.PathElementBase;
this.base(e);
this.path=function(k){var g=4*((Math.sqrt(2)-1)/3);
var j=this.attribute("rx").toPixels("x");
var f=this.attribute("ry").toPixels("y");
var h=this.attribute("cx").toPixels("x");
var l=this.attribute("cy").toPixels("y");
if(k!=null){k.beginPath();
k.moveTo(h,l-f);
k.bezierCurveTo(h+(g*j),l-f,h+j,l-(g*f),h+j,l);
k.bezierCurveTo(h+j,l+(g*f),h+(g*j),l+f,h,l+f);
k.bezierCurveTo(h-(g*j),l+f,h-j,l+(g*f),h-j,l);
k.bezierCurveTo(h-j,l-(g*f),h-(g*j),l-f,h,l-f);
k.closePath();
}return new c.BoundingBox(h-j,l-f,h+j,l+f);
};
};
c.Element.ellipse.prototype=new c.Element.PathElementBase;
c.Element.line=function(e){this.base=c.Element.PathElementBase;
this.base(e);
this.getPoints=function(){return[new c.Point(this.attribute("x1").toPixels("x"),this.attribute("y1").toPixels("y")),new c.Point(this.attribute("x2").toPixels("x"),this.attribute("y2").toPixels("y"))];
};
this.path=function(f){var g=this.getPoints();
if(f!=null){f.beginPath();
f.moveTo(g[0].x,g[0].y);
f.lineTo(g[1].x,g[1].y);
}return new c.BoundingBox(g[0].x,g[0].y,g[1].x,g[1].y);
};
this.getMarkers=function(){var g=this.getPoints();
var f=g[0].angleTo(g[1]);
return[[g[0],f],[g[1],f]];
};
};
c.Element.line.prototype=new c.Element.PathElementBase;
c.Element.polyline=function(e){this.base=c.Element.PathElementBase;
this.base(e);
this.points=c.CreatePath(this.attribute("points").value);
this.path=function(f){var h=new c.BoundingBox(this.points[0].x,this.points[0].y);
if(f!=null){f.beginPath();
f.moveTo(this.points[0].x,this.points[0].y);
}for(var g=1;
g<this.points.length;
g++){h.addPoint(this.points[g].x,this.points[g].y);
if(f!=null){f.lineTo(this.points[g].x,this.points[g].y);
}}return h;
};
this.getMarkers=function(){var g=[];
for(var f=0;
f<this.points.length-1;
f++){g.push([this.points[f],this.points[f].angleTo(this.points[f+1])]);
}g.push([this.points[this.points.length-1],g[g.length-1][1]]);
return g;
};
};
c.Element.polyline.prototype=new c.Element.PathElementBase;
c.Element.polygon=function(e){this.base=c.Element.polyline;
this.base(e);
this.basePath=this.path;
this.path=function(f){var g=this.basePath(f);
if(f!=null){f.lineTo(this.points[0].x,this.points[0].y);
f.closePath();
}return g;
};
};
c.Element.polygon.prototype=new c.Element.polyline;
c.Element.path=function(e){this.base=c.Element.PathElementBase;
this.base(e);
var f=this.attribute("d").value;
f=f.replace(/,/gm," ");
f=f.replace(/([MmZzLlHhVvCcSsQqTtAa])([MmZzLlHhVvCcSsQqTtAa])/gm,"$1 $2");
f=f.replace(/([MmZzLlHhVvCcSsQqTtAa])([MmZzLlHhVvCcSsQqTtAa])/gm,"$1 $2");
f=f.replace(/([MmZzLlHhVvCcSsQqTtAa])([^\s])/gm,"$1 $2");
f=f.replace(/([^\s])([MmZzLlHhVvCcSsQqTtAa])/gm,"$1 $2");
f=f.replace(/([0-9])([+\-])/gm,"$1 $2");
f=f.replace(/(\.[0-9]*)(\.)/gm,"$1 $2");
f=f.replace(/([Aa](\s+[0-9]+){3})\s+([01])\s*([01])/gm,"$1 $3 $4 ");
f=c.compressSpaces(f);
f=c.trim(f);
this.PathParser=new (function(g){this.tokens=g.split(" ");
this.reset=function(){this.i=-1;
this.command="";
this.previousCommand="";
this.start=new c.Point(0,0);
this.control=new c.Point(0,0);
this.current=new c.Point(0,0);
this.points=[];
this.angles=[];
};
this.isEnd=function(){return this.i>=this.tokens.length-1;
};
this.isCommandOrEnd=function(){if(this.isEnd()){return true;
}return this.tokens[this.i+1].match(/^[A-Za-z]$/)!=null;
};
this.isRelativeCommand=function(){switch(this.command){case"m":case"l":case"h":case"v":case"c":case"s":case"q":case"t":case"a":case"z":return true;
break;
}return false;
};
this.getToken=function(){this.i++;
return this.tokens[this.i];
};
this.getScalar=function(){return parseFloat(this.getToken());
};
this.nextCommand=function(){this.previousCommand=this.command;
this.command=this.getToken();
};
this.getPoint=function(){var h=new c.Point(this.getScalar(),this.getScalar());
return this.makeAbsolute(h);
};
this.getAsControlPoint=function(){var h=this.getPoint();
this.control=h;
return h;
};
this.getAsCurrentPoint=function(){var h=this.getPoint();
this.current=h;
return h;
};
this.getReflectedControlPoint=function(){if(this.previousCommand.toLowerCase()!="c"&&this.previousCommand.toLowerCase()!="s"&&this.previousCommand.toLowerCase()!="q"&&this.previousCommand.toLowerCase()!="t"){return this.current;
}var h=new c.Point(2*this.current.x-this.control.x,2*this.current.y-this.control.y);
return h;
};
this.makeAbsolute=function(h){if(this.isRelativeCommand()){h.x+=this.current.x;
h.y+=this.current.y;
}return h;
};
this.addMarker=function(j,k,h){if(h!=null&&this.angles.length>0&&this.angles[this.angles.length-1]==null){this.angles[this.angles.length-1]=this.points[this.points.length-1].angleTo(h);
}this.addMarkerAngle(j,k==null?null:k.angleTo(j));
};
this.addMarkerAngle=function(j,h){this.points.push(j);
this.angles.push(h);
};
this.getMarkerPoints=function(){return this.points;
};
this.getMarkerAngles=function(){for(var k=0;
k<this.angles.length;
k++){if(this.angles[k]==null){for(var h=k+1;
h<this.angles.length;
h++){if(this.angles[h]!=null){this.angles[k]=this.angles[h];
break;
}}}}return this.angles;
};
})(f);
this.path=function(J){var N=this.PathParser;
N.reset();
var o=new c.BoundingBox();
if(J!=null){J.beginPath();
}while(!N.isEnd()){N.nextCommand();
switch(N.command){case"M":case"m":var Q=N.getAsCurrentPoint();
N.addMarker(Q);
o.addPoint(Q.x,Q.y);
if(J!=null){J.moveTo(Q.x,Q.y);
}N.start=N.current;
while(!N.isCommandOrEnd()){var Q=N.getAsCurrentPoint();
N.addMarker(Q,N.start);
o.addPoint(Q.x,Q.y);
if(J!=null){J.lineTo(Q.x,Q.y);
}}break;
case"L":case"l":while(!N.isCommandOrEnd()){var O=N.current;
var Q=N.getAsCurrentPoint();
N.addMarker(Q,O);
o.addPoint(Q.x,Q.y);
if(J!=null){J.lineTo(Q.x,Q.y);
}}break;
case"H":case"h":while(!N.isCommandOrEnd()){var y=new c.Point((N.isRelativeCommand()?N.current.x:0)+N.getScalar(),N.current.y);
N.addMarker(y,N.current);
N.current=y;
o.addPoint(N.current.x,N.current.y);
if(J!=null){J.lineTo(N.current.x,N.current.y);
}}break;
case"V":case"v":while(!N.isCommandOrEnd()){var y=new c.Point(N.current.x,(N.isRelativeCommand()?N.current.y:0)+N.getScalar());
N.addMarker(y,N.current);
N.current=y;
o.addPoint(N.current.x,N.current.y);
if(J!=null){J.lineTo(N.current.x,N.current.y);
}}break;
case"C":case"c":while(!N.isCommandOrEnd()){var q=N.current;
var n=N.getPoint();
var E=N.getAsControlPoint();
var g=N.getAsCurrentPoint();
N.addMarker(g,E,n);
o.addBezierCurve(q.x,q.y,n.x,n.y,E.x,E.y,g.x,g.y);
if(J!=null){J.bezierCurveTo(n.x,n.y,E.x,E.y,g.x,g.y);
}}break;
case"S":case"s":while(!N.isCommandOrEnd()){var q=N.current;
var n=N.getReflectedControlPoint();
var E=N.getAsControlPoint();
var g=N.getAsCurrentPoint();
N.addMarker(g,E,n);
o.addBezierCurve(q.x,q.y,n.x,n.y,E.x,E.y,g.x,g.y);
if(J!=null){J.bezierCurveTo(n.x,n.y,E.x,E.y,g.x,g.y);
}}break;
case"Q":case"q":while(!N.isCommandOrEnd()){var q=N.current;
var E=N.getAsControlPoint();
var g=N.getAsCurrentPoint();
N.addMarker(g,E,E);
o.addQuadraticCurve(q.x,q.y,E.x,E.y,g.x,g.y);
if(J!=null){J.quadraticCurveTo(E.x,E.y,g.x,g.y);
}}break;
case"T":case"t":while(!N.isCommandOrEnd()){var q=N.current;
var E=N.getReflectedControlPoint();
N.control=E;
var g=N.getAsCurrentPoint();
N.addMarker(g,E,E);
o.addQuadraticCurve(q.x,q.y,E.x,E.y,g.x,g.y);
if(J!=null){J.quadraticCurveTo(E.x,E.y,g.x,g.y);
}}break;
case"A":case"a":while(!N.isCommandOrEnd()){var q=N.current;
var F=N.getScalar();
var I=N.getScalar();
var H=N.getScalar()*(Math.PI/180);
var t=N.getScalar();
var M=N.getScalar();
var g=N.getAsCurrentPoint();
var S=new c.Point(Math.cos(H)*(q.x-g.x)/2+Math.sin(H)*(q.y-g.y)/2,-Math.sin(H)*(q.x-g.x)/2+Math.cos(H)*(q.y-g.y)/2);
var L=Math.pow(S.x,2)/Math.pow(F,2)+Math.pow(S.y,2)/Math.pow(I,2);
if(L>1){F*=Math.sqrt(L);
I*=Math.sqrt(L);
}var D=(t==M?-1:1)*Math.sqrt(((Math.pow(F,2)*Math.pow(I,2))-(Math.pow(F,2)*Math.pow(S.y,2))-(Math.pow(I,2)*Math.pow(S.x,2)))/(Math.pow(F,2)*Math.pow(S.y,2)+Math.pow(I,2)*Math.pow(S.x,2)));
if(isNaN(D)){D=0;
}var B=new c.Point(D*F*S.y/I,D*-I*S.x/F);
var T=new c.Point((q.x+g.x)/2+Math.cos(H)*B.x-Math.sin(H)*B.y,(q.y+g.y)/2+Math.sin(H)*B.x+Math.cos(H)*B.y);
var j=function(l){return Math.sqrt(Math.pow(l[0],2)+Math.pow(l[1],2));
};
var h=function(m,l){return(m[0]*l[0]+m[1]*l[1])/(j(m)*j(l));
};
var x=function(m,l){return(m[0]*l[1]<m[1]*l[0]?-1:1)*Math.acos(h(m,l));
};
var z=x([1,0],[(S.x-B.x)/F,(S.y-B.y)/I]);
var K=[(S.x-B.x)/F,(S.y-B.y)/I];
var G=[(-S.x-B.x)/F,(-S.y-B.y)/I];
var R=x(K,G);
if(h(K,G)<=-1){R=Math.PI;
}if(h(K,G)>=1){R=0;
}var A=1-M?1:-1;
var C=z+A*(R/2);
var w=new c.Point(T.x+F*Math.cos(C),T.y+I*Math.sin(C));
N.addMarkerAngle(w,C-A*Math.PI/2);
N.addMarkerAngle(g,C-A*Math.PI);
o.addPoint(g.x,g.y);
if(J!=null){var h=F>I?F:I;
var P=F>I?1:F/I;
var k=F>I?I/F:1;
J.translate(T.x,T.y);
J.rotate(H);
J.scale(P,k);
J.arc(0,0,h,z,z+R,1-M);
J.scale(1/P,1/k);
J.rotate(-H);
J.translate(-T.x,-T.y);
}}break;
case"Z":case"z":if(J!=null){J.closePath();
}N.current=N.start;
}}return o;
};
this.getMarkers=function(){var h=this.PathParser.getMarkerPoints();
var k=this.PathParser.getMarkerAngles();
var j=[];
for(var g=0;
g<h.length;
g++){j.push([h[g],k[g]]);
}return j;
};
};
c.Element.path.prototype=new c.Element.PathElementBase;
c.Element.pattern=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.createPattern=function(n,f){var o=this.attribute("width").toPixels("x",true);
var m=this.attribute("height").toPixels("y",true);
var k=new c.Element.svg();
k.attributes["viewBox"]=new c.Property("viewBox",this.attribute("viewBox").value);
k.attributes["width"]=new c.Property("width",o+"px");
k.attributes["height"]=new c.Property("height",m+"px");
k.attributes["transform"]=new c.Property("transform",this.attribute("patternTransform").value);
k.children=this.children;
var h=document.createElement("canvas");
h.width=o;
h.height=m;
var p=h.getContext("2d");
if(this.attribute("x").hasValue()&&this.attribute("y").hasValue()){p.translate(this.attribute("x").toPixels("x",true),this.attribute("y").toPixels("y",true));
}for(var l=-1;
l<=1;
l++){for(var j=-1;
j<=1;
j++){p.save();
p.translate(l*h.width,j*h.height);
k.render(p);
p.restore();
}}var g=n.createPattern(h,"repeat");
return g;
};
};
c.Element.pattern.prototype=new c.Element.ElementBase;
c.Element.marker=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.baseRender=this.render;
this.render=function(g,f,j){g.translate(f.x,f.y);
if(this.attribute("orient").valueOrDefault("auto")=="auto"){g.rotate(j);
}if(this.attribute("markerUnits").valueOrDefault("strokeWidth")=="strokeWidth"){g.scale(g.lineWidth,g.lineWidth);
}g.save();
var h=new c.Element.svg();
h.attributes["viewBox"]=new c.Property("viewBox",this.attribute("viewBox").value);
h.attributes["refX"]=new c.Property("refX",this.attribute("refX").value);
h.attributes["refY"]=new c.Property("refY",this.attribute("refY").value);
h.attributes["width"]=new c.Property("width",this.attribute("markerWidth").value);
h.attributes["height"]=new c.Property("height",this.attribute("markerHeight").value);
h.attributes["fill"]=new c.Property("fill",this.attribute("fill").valueOrDefault("black"));
h.attributes["stroke"]=new c.Property("stroke",this.attribute("stroke").valueOrDefault("none"));
h.children=this.children;
h.render(g);
g.restore();
if(this.attribute("markerUnits").valueOrDefault("strokeWidth")=="strokeWidth"){g.scale(1/g.lineWidth,1/g.lineWidth);
}if(this.attribute("orient").valueOrDefault("auto")=="auto"){g.rotate(-j);
}g.translate(-f.x,-f.y);
};
};
c.Element.marker.prototype=new c.Element.ElementBase;
c.Element.defs=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.render=function(f){};
};
c.Element.defs.prototype=new c.Element.ElementBase;
c.Element.GradientBase=function(f){this.base=c.Element.ElementBase;
this.base(f);
this.gradientUnits=this.attribute("gradientUnits").valueOrDefault("objectBoundingBox");
this.stops=[];
for(var e=0;
e<this.children.length;
e++){var g=this.children[e];
if(g.type=="stop"){this.stops.push(g);
}}this.getGradient=function(){};
this.createGradient=function(u,l,h){var t=this;
if(this.getHrefAttribute().hasValue()){t=this.getHrefAttribute().getDefinition();
}var k=function(v){if(h.hasValue()){var w=new c.Property("color",v);
return w.addOpacity(h).value;
}return v;
};
var n=this.getGradient(u,l);
if(n==null){return k(t.stops[t.stops.length-1].color);
}for(var m=0;
m<t.stops.length;
m++){n.addColorStop(t.stops[m].offset,k(t.stops[m].color));
}if(this.attribute("gradientTransform").hasValue()){var p=c.ViewPort.viewPorts[0];
var q=new c.Element.rect();
q.attributes["x"]=new c.Property("x",-c.MAX_VIRTUAL_PIXELS/3);
q.attributes["y"]=new c.Property("y",-c.MAX_VIRTUAL_PIXELS/3);
q.attributes["width"]=new c.Property("width",c.MAX_VIRTUAL_PIXELS);
q.attributes["height"]=new c.Property("height",c.MAX_VIRTUAL_PIXELS);
var s=new c.Element.g();
s.attributes["transform"]=new c.Property("transform",this.attribute("gradientTransform").value);
s.children=[q];
var r=new c.Element.svg();
r.attributes["x"]=new c.Property("x",0);
r.attributes["y"]=new c.Property("y",0);
r.attributes["width"]=new c.Property("width",p.width);
r.attributes["height"]=new c.Property("height",p.height);
r.children=[s];
var o=document.createElement("canvas");
o.width=p.width;
o.height=p.height;
var j=o.getContext("2d");
j.fillStyle=n;
r.render(j);
return j.createPattern(o,"no-repeat");
}return n;
};
};
c.Element.GradientBase.prototype=new c.Element.ElementBase;
c.Element.linearGradient=function(e){this.base=c.Element.GradientBase;
this.base(e);
this.getGradient=function(f,m){var l=this.gradientUnits=="objectBoundingBox"?m.getBoundingBox():null;
if(!this.attribute("x1").hasValue()&&!this.attribute("y1").hasValue()&&!this.attribute("x2").hasValue()&&!this.attribute("y2").hasValue()){this.attribute("x1",true).value=0;
this.attribute("y1",true).value=0;
this.attribute("x2",true).value=1;
this.attribute("y2",true).value=0;
}var h=(this.gradientUnits=="objectBoundingBox"?l.x()+l.width()*this.attribute("x1").numValue():this.attribute("x1").toPixels("x"));
var k=(this.gradientUnits=="objectBoundingBox"?l.y()+l.height()*this.attribute("y1").numValue():this.attribute("y1").toPixels("y"));
var g=(this.gradientUnits=="objectBoundingBox"?l.x()+l.width()*this.attribute("x2").numValue():this.attribute("x2").toPixels("x"));
var j=(this.gradientUnits=="objectBoundingBox"?l.y()+l.height()*this.attribute("y2").numValue():this.attribute("y2").toPixels("y"));
if(h==g&&k==j){return null;
}return f.createLinearGradient(h,k,g,j);
};
};
c.Element.linearGradient.prototype=new c.Element.GradientBase;
c.Element.radialGradient=function(e){this.base=c.Element.GradientBase;
this.base(e);
this.getGradient=function(f,g){var k=g.getBoundingBox();
if(!this.attribute("cx").hasValue()){this.attribute("cx",true).value="50%";
}if(!this.attribute("cy").hasValue()){this.attribute("cy",true).value="50%";
}if(!this.attribute("r").hasValue()){this.attribute("r",true).value="50%";
}var n=(this.gradientUnits=="objectBoundingBox"?k.x()+k.width()*this.attribute("cx").numValue():this.attribute("cx").toPixels("x"));
var l=(this.gradientUnits=="objectBoundingBox"?k.y()+k.height()*this.attribute("cy").numValue():this.attribute("cy").toPixels("y"));
var j=n;
var h=l;
if(this.attribute("fx").hasValue()){j=(this.gradientUnits=="objectBoundingBox"?k.x()+k.width()*this.attribute("fx").numValue():this.attribute("fx").toPixels("x"));
}if(this.attribute("fy").hasValue()){h=(this.gradientUnits=="objectBoundingBox"?k.y()+k.height()*this.attribute("fy").numValue():this.attribute("fy").toPixels("y"));
}var m=(this.gradientUnits=="objectBoundingBox"?(k.width()+k.height())/2*this.attribute("r").numValue():this.attribute("r").toPixels());
return f.createRadialGradient(j,h,0,n,l,m);
};
};
c.Element.radialGradient.prototype=new c.Element.GradientBase;
c.Element.stop=function(f){this.base=c.Element.ElementBase;
this.base(f);
this.offset=this.attribute("offset").numValue();
if(this.offset<0){this.offset=0;
}if(this.offset>1){this.offset=1;
}var e=this.style("stop-color");
if(this.style("stop-opacity").hasValue()){e=e.addOpacity(this.style("stop-opacity"));
}this.color=e.value;
};
c.Element.stop.prototype=new c.Element.ElementBase;
c.Element.AnimateBase=function(e){this.base=c.Element.ElementBase;
this.base(e);
c.Animations.push(this);
this.duration=0;
this.begin=this.attribute("begin").toMilliseconds();
this.maxDuration=this.begin+this.attribute("dur").toMilliseconds();
this.getProperty=function(){var g=this.attribute("attributeType").value;
var f=this.attribute("attributeName").value;
if(g=="CSS"){return this.parent.style(f,true);
}return this.parent.attribute(f,true);
};
this.initialValue=null;
this.initialUnits="";
this.removed=false;
this.calcValue=function(){return"";
};
this.update=function(j){if(this.initialValue==null){this.initialValue=this.getProperty().value;
this.initialUnits=this.getProperty().getUnits();
}if(this.duration>this.maxDuration){if(this.attribute("repeatCount").value=="indefinite"||this.attribute("repeatDur").value=="indefinite"){this.duration=0;
}else{if(this.attribute("fill").valueOrDefault("remove")=="freeze"&&!this.frozen){this.frozen=true;
this.parent.animationFrozen=true;
this.parent.animationFrozenValue=this.getProperty().value;
}else{if(this.attribute("fill").valueOrDefault("remove")=="remove"&&!this.removed){this.removed=true;
this.getProperty().value=this.parent.animationFrozen?this.parent.animationFrozenValue:this.initialValue;
return true;
}}}return false;
}this.duration=this.duration+j;
var f=false;
if(this.begin<this.duration){var h=this.calcValue();
if(this.attribute("type").hasValue()){var g=this.attribute("type").value;
h=g+"("+h+")";
}this.getProperty().value=h;
f=true;
}return f;
};
this.from=this.attribute("from");
this.to=this.attribute("to");
this.values=this.attribute("values");
if(this.values.hasValue()){this.values.value=this.values.value.split(";");
}this.progress=function(){var g={progress:(this.duration-this.begin)/(this.maxDuration-this.begin)};
if(this.values.hasValue()){var j=g.progress*(this.values.value.length-1);
var h=Math.floor(j),f=Math.ceil(j);
g.from=new c.Property("from",parseFloat(this.values.value[h]));
g.to=new c.Property("to",parseFloat(this.values.value[f]));
g.progress=(j-h)/(f-h);
}else{g.from=this.from;
g.to=this.to;
}return g;
};
};
c.Element.AnimateBase.prototype=new c.Element.ElementBase;
c.Element.animate=function(e){this.base=c.Element.AnimateBase;
this.base(e);
this.calcValue=function(){var g=this.progress();
var f=g.from.numValue()+(g.to.numValue()-g.from.numValue())*g.progress;
return f+this.initialUnits;
};
};
c.Element.animate.prototype=new c.Element.AnimateBase;
c.Element.animateColor=function(e){this.base=c.Element.AnimateBase;
this.base(e);
this.calcValue=function(){var l=this.progress();
var f=new RGBColor(l.from.value);
var h=new RGBColor(l.to.value);
if(f.ok&&h.ok){var j=f.r+(h.r-f.r)*l.progress;
var k=f.g+(h.g-f.g)*l.progress;
var m=f.b+(h.b-f.b)*l.progress;
return"rgb("+parseInt(j,10)+","+parseInt(k,10)+","+parseInt(m,10)+")";
}return this.attribute("from").value;
};
};
c.Element.animateColor.prototype=new c.Element.AnimateBase;
c.Element.animateTransform=function(e){this.base=c.Element.AnimateBase;
this.base(e);
this.calcValue=function(){var g=this.progress();
var k=c.ToNumberArray(g.from.value);
var j=c.ToNumberArray(g.to.value);
var h="";
for(var f=0;
f<k.length;
f++){h+=k[f]+(j[f]-k[f])*g.progress+" ";
}return h;
};
};
c.Element.animateTransform.prototype=new c.Element.animate;
c.Element.font=function(f){this.base=c.Element.ElementBase;
this.base(f);
this.horizAdvX=this.attribute("horiz-adv-x").numValue();
this.isRTL=false;
this.isArabic=false;
this.fontFace=null;
this.missingGlyph=null;
this.glyphs=[];
for(var e=0;
e<this.children.length;
e++){var g=this.children[e];
if(g.type=="font-face"){this.fontFace=g;
if(g.style("font-family").hasValue()){c.Definitions[g.style("font-family").value]=this;
}}else{if(g.type=="missing-glyph"){this.missingGlyph=g;
}else{if(g.type=="glyph"){if(g.arabicForm!=""){this.isRTL=true;
this.isArabic=true;
if(typeof(this.glyphs[g.unicode])=="undefined"){this.glyphs[g.unicode]=[];
}this.glyphs[g.unicode][g.arabicForm]=g;
}else{this.glyphs[g.unicode]=g;
}}}}}};
c.Element.font.prototype=new c.Element.ElementBase;
c.Element.fontface=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.ascent=this.attribute("ascent").value;
this.descent=this.attribute("descent").value;
this.unitsPerEm=this.attribute("units-per-em").numValue();
};
c.Element.fontface.prototype=new c.Element.ElementBase;
c.Element.missingglyph=function(e){this.base=c.Element.path;
this.base(e);
this.horizAdvX=0;
};
c.Element.missingglyph.prototype=new c.Element.path;
c.Element.glyph=function(e){this.base=c.Element.path;
this.base(e);
this.horizAdvX=this.attribute("horiz-adv-x").numValue();
this.unicode=this.attribute("unicode").value;
this.arabicForm=this.attribute("arabic-form").value;
};
c.Element.glyph.prototype=new c.Element.path;
c.Element.text=function(e){this.captureTextNodes=true;
this.base=c.Element.RenderedElementBase;
this.base(e);
this.baseSetContext=this.setContext;
this.setContext=function(f){this.baseSetContext(f);
var g=this.style("dominant-baseline").toTextBaseline();
if(g==null){g=this.style("alignment-baseline").toTextBaseline();
}if(g!=null){f.textBaseline=g;
}};
this.getBoundingBox=function(){var f=this.attribute("x").toPixels("x");
var h=this.attribute("y").toPixels("y");
var g=this.parent.style("font-size").numValueOrDefault(c.Font.Parse(c.ctx.font).fontSize);
return new c.BoundingBox(f,h-g,f+Math.floor(g*2/3)*this.children[0].getText().length,h);
};
this.renderChildren=function(f){this.x=this.attribute("x").toPixels("x");
this.y=this.attribute("y").toPixels("y");
this.x+=this.getAnchorDelta(f,this,0);
for(var g=0;
g<this.children.length;
g++){this.renderChild(f,this,g);
}};
this.getAnchorDelta=function(g,l,m){var f=this.style("text-anchor").valueOrDefault("start");
if(f!="start"){var j=0;
for(var h=m;
h<l.children.length;
h++){var k=l.children[h];
if(h>m&&k.attribute("x").hasValue()){break;
}j+=k.measureTextRecursive(g);
}return -1*(f=="end"?j:j/2);
}return 0;
};
this.renderChild=function(f,h,g){var j=h.children[g];
if(j.attribute("x").hasValue()){j.x=j.attribute("x").toPixels("x")+this.getAnchorDelta(f,h,g);
if(j.attribute("dx").hasValue()){j.x+=j.attribute("dx").toPixels("x");
}}else{if(this.attribute("dx").hasValue()){this.x+=this.attribute("dx").toPixels("x");
}if(j.attribute("dx").hasValue()){this.x+=j.attribute("dx").toPixels("x");
}j.x=this.x;
}this.x=j.x+j.measureText(f);
if(j.attribute("y").hasValue()){j.y=j.attribute("y").toPixels("y");
if(j.attribute("dy").hasValue()){j.y+=j.attribute("dy").toPixels("y");
}}else{if(this.attribute("dy").hasValue()){this.y+=this.attribute("dy").toPixels("y");
}if(j.attribute("dy").hasValue()){this.y+=j.attribute("dy").toPixels("y");
}j.y=this.y;
}this.y=j.y;
j.render(f);
for(var g=0;
g<j.children.length;
g++){this.renderChild(f,j,g);
}};
};
c.Element.text.prototype=new c.Element.RenderedElementBase;
c.Element.TextElementBase=function(e){this.base=c.Element.RenderedElementBase;
this.base(e);
this.getGlyph=function(h,g,k){var f=g[k];
var l=null;
if(h.isArabic){var j="isolated";
if((k==0||g[k-1]==" ")&&k<g.length-2&&g[k+1]!=" "){j="terminal";
}if(k>0&&g[k-1]!=" "&&k<g.length-2&&g[k+1]!=" "){j="medial";
}if(k>0&&g[k-1]!=" "&&(k==g.length-1||g[k+1]==" ")){j="initial";
}if(typeof(h.glyphs[f])!="undefined"){l=h.glyphs[f][j];
if(l==null&&h.glyphs[f].type=="glyph"){l=h.glyphs[f];
}}}else{l=h.glyphs[f];
}if(l==null){l=h.missingGlyph;
}return l;
};
this.renderChildren=function(l){var j=this.parent.style("font-family").getDefinition();
if(j!=null){var m=this.parent.style("font-size").numValueOrDefault(c.Font.Parse(c.ctx.font).fontSize);
var f=this.parent.style("font-style").valueOrDefault(c.Font.Parse(c.ctx.font).fontStyle);
var k=this.getText();
if(j.isRTL){k=k.split("").reverse().join("");
}var n=c.ToNumberArray(this.parent.attribute("dx").value);
for(var g=0;
g<k.length;
g++){var h=this.getGlyph(j,k,g);
var p=m/j.fontFace.unitsPerEm;
l.translate(this.x,this.y);
l.scale(p,-p);
var o=l.lineWidth;
l.lineWidth=l.lineWidth*j.fontFace.unitsPerEm/m;
if(f=="italic"){l.transform(1,0,0.4,1,0,0);
}h.render(l);
if(f=="italic"){l.transform(1,0,-0.4,1,0,0);
}l.lineWidth=o;
l.scale(1/p,-1/p);
l.translate(-this.x,-this.y);
this.x+=m*(h.horizAdvX||j.horizAdvX)/j.fontFace.unitsPerEm;
if(typeof(n[g])!="undefined"&&!isNaN(n[g])){this.x+=n[g];
}}return;
}if(l.fillStyle!=""){l.fillText(c.compressSpaces(this.getText()),this.x,this.y);
}if(l.strokeStyle!=""){l.strokeText(c.compressSpaces(this.getText()),this.x,this.y);
}};
this.getText=function(){};
this.measureTextRecursive=function(f){var h=this.measureText(f);
for(var g=0;
g<this.children.length;
g++){h+=this.children[g].measureTextRecursive(f);
}return h;
};
this.measureText=function(l){var j=this.parent.style("font-family").getDefinition();
if(j!=null){var m=this.parent.style("font-size").numValueOrDefault(c.Font.Parse(c.ctx.font).fontSize);
var p=0;
var k=this.getText();
if(j.isRTL){k=k.split("").reverse().join("");
}var n=c.ToNumberArray(this.parent.attribute("dx").value);
for(var g=0;
g<k.length;
g++){var h=this.getGlyph(j,k,g);
p+=(h.horizAdvX||j.horizAdvX)*m/j.fontFace.unitsPerEm;
if(typeof(n[g])!="undefined"&&!isNaN(n[g])){p+=n[g];
}}return p;
}var o=c.compressSpaces(this.getText());
if(!l.measureText){return o.length*10;
}l.save();
this.setContext(l);
var f=l.measureText(o).width;
l.restore();
return f;
};
};
c.Element.TextElementBase.prototype=new c.Element.RenderedElementBase;
c.Element.tspan=function(e){this.captureTextNodes=true;
this.base=c.Element.TextElementBase;
this.base(e);
this.text=e.nodeValue||e.text||"";
this.getText=function(){return this.text;
};
};
c.Element.tspan.prototype=new c.Element.TextElementBase;
c.Element.tref=function(e){this.base=c.Element.TextElementBase;
this.base(e);
this.getText=function(){var f=this.getHrefAttribute().getDefinition();
if(f!=null){return f.children[0].getText();
}};
};
c.Element.tref.prototype=new c.Element.TextElementBase;
c.Element.a=function(f){this.base=c.Element.TextElementBase;
this.base(f);
this.hasText=true;
for(var e=0;
e<f.childNodes.length;
e++){if(f.childNodes[e].nodeType!=3){this.hasText=false;
}}this.text=this.hasText?f.childNodes[0].nodeValue:"";
this.getText=function(){return this.text;
};
this.baseRenderChildren=this.renderChildren;
this.renderChildren=function(h){if(this.hasText){this.baseRenderChildren(h);
var k=new c.Property("fontSize",c.Font.Parse(c.ctx.font).fontSize);
c.Mouse.checkBoundingBox(this,new c.BoundingBox(this.x,this.y-k.toPixels("y"),this.x+this.measureText(h),this.y));
}else{var j=new c.Element.g();
j.children=this.children;
j.parent=this;
j.render(h);
}};
this.onclick=function(){window.open(this.getHrefAttribute().value);
};
this.onmousemove=function(){c.ctx.canvas.style.cursor="pointer";
};
};
c.Element.a.prototype=new c.Element.TextElementBase;
c.Element.image=function(g){this.base=c.Element.RenderedElementBase;
this.base(g);
var f=this.getHrefAttribute().value;
if(f==""){return;
}var h=f.match(/\.svg$/);
c.Images.push(this);
this.loaded=false;
if(!h){this.img=document.createElement("img");
if(c.opts["useCORS"]==true){this.img.crossOrigin="Anonymous";
}var e=this;
this.img.onload=function(){e.loaded=true;
};
this.img.onerror=function(){c.log('ERROR: image "'+f+'" not found');
e.loaded=true;
};
this.img.src=f;
}else{this.img=c.ajax(f);
this.loaded=true;
}this.renderChildren=function(j){var n=this.attribute("x").toPixels("x");
var l=this.attribute("y").toPixels("y");
var k=this.attribute("width").toPixels("x");
var m=this.attribute("height").toPixels("y");
if(k==0||m==0){return;
}j.save();
if(h){j.drawSvg(this.img,n,l,k,m);
}else{j.translate(n,l);
c.AspectRatio(j,this.attribute("preserveAspectRatio").value,k,this.img.width,m,this.img.height,0,0);
j.drawImage(this.img,0,0);
}j.restore();
};
this.getBoundingBox=function(){var k=this.attribute("x").toPixels("x");
var m=this.attribute("y").toPixels("y");
var l=this.attribute("width").toPixels("x");
var j=this.attribute("height").toPixels("y");
return new c.BoundingBox(k,m,k+l,m+j);
};
};
c.Element.image.prototype=new c.Element.RenderedElementBase;
c.Element.g=function(e){this.base=c.Element.RenderedElementBase;
this.base(e);
this.getBoundingBox=function(){var g=new c.BoundingBox();
for(var f=0;
f<this.children.length;
f++){g.addBoundingBox(this.children[f].getBoundingBox());
}return g;
};
};
c.Element.g.prototype=new c.Element.RenderedElementBase;
c.Element.symbol=function(e){this.base=c.Element.RenderedElementBase;
this.base(e);
this.render=function(f){};
};
c.Element.symbol.prototype=new c.Element.RenderedElementBase;
c.Element.style=function(w){this.base=c.Element.ElementBase;
this.base(w);
var D="";
for(var q=0;
q<w.childNodes.length;
q++){D+=w.childNodes[q].nodeValue;
}D=D.replace(/(\/\*([^*]|[\r\n]|(\*+([^*\/]|[\r\n])))*\*+\/)|(^[\s]*\/\/.*)/gm,"");
D=c.compressSpaces(D);
var x=D.split("}");
for(var q=0;
q<x.length;
q++){if(c.trim(x[q])!=""){var u=x[q].split("{");
var h=u[0].split(",");
var e=u[1].split(";");
for(var o=0;
o<h.length;
o++){var z=c.trim(h[o]);
if(z!=""){var g={};
for(var r=0;
r<e.length;
r++){var f=e[r].indexOf(":");
var C=e[r].substr(0,f);
var t=e[r].substr(f+1,e[r].length-f);
if(C!=null&&t!=null){g[c.trim(C)]=new c.Property(c.trim(C),c.trim(t));
}}c.Styles[z]=g;
if(z=="@font-face"){var F=g["font-family"].value.replace(/"/g,"");
var v=g["src"].value.split(",");
for(var p=0;
p<v.length;
p++){if(v[p].indexOf('format("svg")')>0){var n=v[p].indexOf("url");
var m=v[p].indexOf(")",n);
var l=v[p].substr(n+5,m-n-6);
var A=c.parseXml(c.ajax(l));
var y=A.getElementsByTagName("font");
for(var B=0;
B<y.length;
B++){var E=c.CreateElement(y[B]);
c.Definitions[F]=E;
}}}}}}}}};
c.Element.style.prototype=new c.Element.ElementBase;
c.Element.use=function(f){this.base=c.Element.RenderedElementBase;
this.base(f);
this.baseSetContext=this.setContext;
this.setContext=function(g){this.baseSetContext(g);
if(this.attribute("x").hasValue()){g.translate(this.attribute("x").toPixels("x"),0);
}if(this.attribute("y").hasValue()){g.translate(0,this.attribute("y").toPixels("y"));
}};
var e=this.getHrefAttribute().getDefinition();
this.path=function(g){if(e!=null){e.path(g);
}};
this.getBoundingBox=function(){if(e!=null){return e.getBoundingBox();
}};
this.renderChildren=function(g){if(e!=null){var j=e;
if(e.type=="symbol"){j=new c.Element.svg();
j.type="svg";
j.attributes["viewBox"]=new c.Property("viewBox",e.attribute("viewBox").value);
j.attributes["preserveAspectRatio"]=new c.Property("preserveAspectRatio",e.attribute("preserveAspectRatio").value);
j.attributes["overflow"]=new c.Property("overflow",e.attribute("overflow").value);
j.children=e.children;
}if(j.type=="svg"){if(this.attribute("width").hasValue()){j.attributes["width"]=new c.Property("width",this.attribute("width").value);
}if(this.attribute("height").hasValue()){j.attributes["height"]=new c.Property("height",this.attribute("height").value);
}}var h=j.parent;
j.parent=null;
j.render(g);
j.parent=h;
}};
};
c.Element.use.prototype=new c.Element.RenderedElementBase;
c.Element.mask=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.apply=function(o,h){var m=this.attribute("x").toPixels("x");
var l=this.attribute("y").toPixels("y");
var f=this.attribute("width").toPixels("x");
var n=this.attribute("height").toPixels("y");
if(f==0&&n==0){var q=new c.BoundingBox();
for(var j=0;
j<this.children.length;
j++){q.addBoundingBox(this.children[j].getBoundingBox());
}var m=Math.floor(q.x1);
var l=Math.floor(q.y1);
var f=Math.floor(q.width());
var n=Math.floor(q.height());
}var s=h.attribute("mask").value;
h.attribute("mask").value="";
var k=document.createElement("canvas");
k.width=m+f;
k.height=l+n;
var p=k.getContext("2d");
this.renderChildren(p);
var r=document.createElement("canvas");
r.width=m+f;
r.height=l+n;
var g=r.getContext("2d");
h.render(g);
g.globalCompositeOperation="destination-in";
g.fillStyle=p.createPattern(k,"no-repeat");
g.fillRect(0,0,m+f,l+n);
o.fillStyle=g.createPattern(r,"no-repeat");
o.fillRect(0,0,m+f,l+n);
h.attribute("mask").value=s;
};
this.render=function(f){};
};
c.Element.mask.prototype=new c.Element.ElementBase;
c.Element.clipPath=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.apply=function(f){for(var h=0;
h<this.children.length;
h++){var j=this.children[h];
if(typeof(j.path)!="undefined"){var g=null;
if(j.attribute("transform").hasValue()){g=new c.Transform(j.attribute("transform").value);
g.apply(f);
}j.path(f);
f.clip();
if(g){g.unapply(f);
}}}};
this.render=function(f){};
};
c.Element.clipPath.prototype=new c.Element.ElementBase;
c.Element.filter=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.apply=function(h,l){var m=l.getBoundingBox();
var f=Math.floor(m.x1);
var o=Math.floor(m.y1);
var j=Math.floor(m.width());
var g=Math.floor(m.height());
var k=l.style("filter").value;
l.style("filter").value="";
var t=0,p=0;
for(var s=0;
s<this.children.length;
s++){var r=this.children[s].extraFilterDistance||0;
t=Math.max(t,r);
p=Math.max(p,r);
}var n=document.createElement("canvas");
n.width=j+2*t;
n.height=g+2*p;
var q=n.getContext("2d");
q.translate(-f+t,-o+p);
l.render(q);
for(var s=0;
s<this.children.length;
s++){this.children[s].apply(q,0,0,j+2*t,g+2*p);
}h.drawImage(n,0,0,j+2*t,g+2*p,f-t,o-p,j+2*t,g+2*p);
l.style("filter",true).value=k;
};
this.render=function(f){};
};
c.Element.filter.prototype=new c.Element.ElementBase;
c.Element.feMorphology=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.apply=function(g,k,j,h,f){};
};
c.Element.feMorphology.prototype=new c.Element.ElementBase;
c.Element.feComposite=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.apply=function(g,k,j,h,f){};
};
c.Element.feComposite.prototype=new c.Element.ElementBase;
c.Element.feColorMatrix=function(f){this.base=c.Element.ElementBase;
this.base(f);
var n=c.ToNumberArray(this.attribute("values").value);
switch(this.attribute("type").valueOrDefault("matrix")){case"saturate":var l=n[0];
n=[0.213+0.787*l,0.715-0.715*l,0.072-0.072*l,0,0,0.213-0.213*l,0.715+0.285*l,0.072-0.072*l,0,0,0.213-0.213*l,0.715-0.715*l,0.072+0.928*l,0,0,0,0,0,1,0,0,0,0,0,1];
break;
case"hueRotate":var g=n[0]*Math.PI/180;
var h=function(p,o,m){return p+Math.cos(g)*o+Math.sin(g)*m;
};
n=[h(0.213,0.787,-0.213),h(0.715,-0.715,-0.715),h(0.072,-0.072,0.928),0,0,h(0.213,-0.213,0.143),h(0.715,0.285,0.14),h(0.072,-0.072,-0.283),0,0,h(0.213,-0.213,-0.787),h(0.715,-0.715,0.715),h(0.072,0.928,0.072),0,0,0,0,0,1,0,0,0,0,0,1];
break;
case"luminanceToAlpha":n=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.2125,0.7154,0.0721,0,0,0,0,0,0,1];
break;
}function j(p,o,s,r,m,q){return p[s*r*4+o*4+q];
}function k(s,r,q,m,p,o,t){s[q*m*4+r*4+o]=t;
}function e(p,o){var m=n[p];
return m*(m<0?o-255:o);
}this.apply=function(t,p,r,u,w){var s=t.getImageData(0,0,u,w);
for(var r=0;
r<w;
r++){for(var p=0;
p<u;
p++){var o=j(s.data,p,r,u,w,0);
var q=j(s.data,p,r,u,w,1);
var v=j(s.data,p,r,u,w,2);
var m=j(s.data,p,r,u,w,3);
k(s.data,p,r,u,w,0,e(0,o)+e(1,q)+e(2,v)+e(3,m)+e(4,1));
k(s.data,p,r,u,w,1,e(5,o)+e(6,q)+e(7,v)+e(8,m)+e(9,1));
k(s.data,p,r,u,w,2,e(10,o)+e(11,q)+e(12,v)+e(13,m)+e(14,1));
k(s.data,p,r,u,w,3,e(15,o)+e(16,q)+e(17,v)+e(18,m)+e(19,1));
}}t.clearRect(0,0,u,w);
t.putImageData(s,0,0);
};
};
c.Element.feColorMatrix.prototype=new c.Element.ElementBase;
c.Element.feGaussianBlur=function(e){this.base=c.Element.ElementBase;
this.base(e);
this.blurRadius=Math.floor(this.attribute("stdDeviation").numValue());
this.extraFilterDistance=this.blurRadius;
this.apply=function(g,k,j,h,f){if(typeof(stackBlurCanvasRGBA)=="undefined"){c.log("ERROR: StackBlur.js must be included for blur to work");
return;
}g.canvas.id=c.UniqueId();
g.canvas.style.display="none";
document.body.appendChild(g.canvas);
stackBlurCanvasRGBA(g.canvas.id,k,j,h,f,this.blurRadius);
document.body.removeChild(g.canvas);
};
};
c.Element.feGaussianBlur.prototype=new c.Element.ElementBase;
c.Element.title=function(e){};
c.Element.title.prototype=new c.Element.ElementBase;
c.Element.desc=function(e){};
c.Element.desc.prototype=new c.Element.ElementBase;
c.Element.MISSING=function(e){c.log("ERROR: Element '"+e.nodeName+"' not yet implemented.");
};
c.Element.MISSING.prototype=new c.Element.ElementBase;
c.CreateElement=function(f){var e=f.nodeName.replace(/^[^:]+:/,"");
e=e.replace(/\-/g,"");
var g=null;
if(typeof(c.Element[e])!="undefined"){g=new c.Element[e](f);
}else{g=new c.Element.MISSING(f);
}g.type=f.nodeName;
return g;
};
c.load=function(e,f){c.loadXml(e,c.ajax(f));
};
c.loadXml=function(e,f){c.loadXmlDoc(e,c.parseXml(f));
};
c.loadXmlDoc=function(e,l){c.init(e);
var j=function(m){var n=e.canvas;
while(n){m.x-=n.offsetLeft;
m.y-=n.offsetTop;
n=n.offsetParent;
}if(window.scrollX){m.x+=window.scrollX;
}if(window.scrollY){m.y+=window.scrollY;
}return m;
};
if(c.opts["ignoreMouse"]!=true){e.canvas.onclick=function(m){var n=j(new c.Point(m!=null?m.clientX:event.clientX,m!=null?m.clientY:event.clientY));
c.Mouse.onclick(n.x,n.y);
};
e.canvas.onmousemove=function(m){var n=j(new c.Point(m!=null?m.clientX:event.clientX,m!=null?m.clientY:event.clientY));
c.Mouse.onmousemove(n.x,n.y);
};
}var g=c.CreateElement(l.documentElement);
g.root=true;
var f=true;
var k=function(){c.ViewPort.Clear();
if(e.canvas.parentNode){c.ViewPort.SetCurrent(e.canvas.parentNode.clientWidth,e.canvas.parentNode.clientHeight);
}if(c.opts["ignoreDimensions"]!=true){if(g.style("width").hasValue()){e.canvas.width=g.style("width").toPixels("x");
e.canvas.style.width=e.canvas.width+"px";
}if(g.style("height").hasValue()){e.canvas.height=g.style("height").toPixels("y");
e.canvas.style.height=e.canvas.height+"px";
}}var n=e.canvas.clientWidth||e.canvas.width;
var m=e.canvas.clientHeight||e.canvas.height;
if(c.opts["ignoreDimensions"]==true&&g.style("width").hasValue()&&g.style("height").hasValue()){n=g.style("width").toPixels("x");
m=g.style("height").toPixels("y");
}c.ViewPort.SetCurrent(n,m);
if(c.opts["offsetX"]!=null){g.attribute("x",true).value=c.opts["offsetX"];
}if(c.opts["offsetY"]!=null){g.attribute("y",true).value=c.opts["offsetY"];
}if(c.opts["scaleWidth"]!=null||c.opts["scaleHeight"]!=null){var o=null,p=null,q=c.ToNumberArray(g.attribute("viewBox").value);
if(c.opts["scaleWidth"]!=null){if(g.attribute("width").hasValue()){o=g.attribute("width").toPixels("x")/c.opts["scaleWidth"];
}else{if(!isNaN(q[2])){o=q[2]/c.opts["scaleWidth"];
}}}if(c.opts["scaleHeight"]!=null){if(g.attribute("height").hasValue()){p=g.attribute("height").toPixels("y")/c.opts["scaleHeight"];
}else{if(!isNaN(q[3])){p=q[3]/c.opts["scaleHeight"];
}}}if(o==null){o=p;
}if(p==null){p=o;
}g.attribute("width",true).value=c.opts["scaleWidth"];
g.attribute("height",true).value=c.opts["scaleHeight"];
g.attribute("viewBox",true).value="0 0 "+(n*o)+" "+(m*p);
g.attribute("preserveAspectRatio",true).value="none";
}if(c.opts["ignoreClear"]!=true){e.clearRect(0,0,n,m);
}g.render(e);
if(f){f=false;
if(typeof(c.opts["renderCallback"])=="function"){c.opts["renderCallback"](l);
}}};
var h=true;
if(c.ImagesLoaded()){h=false;
k();
}c.intervalID=setInterval(function(){var n=false;
if(h&&c.ImagesLoaded()){h=false;
n=true;
}if(c.opts["ignoreMouse"]!=true){n=n|c.Mouse.hasEvents();
}if(c.opts["ignoreAnimation"]!=true){for(var m=0;
m<c.Animations.length;
m++){n=n|c.Animations[m].update(1000/c.FRAMERATE);
}}if(typeof(c.opts["forceRedraw"])=="function"){if(c.opts["forceRedraw"]()==true){n=true;
}}if(n){k();
c.Mouse.runEvents();
}},1000/c.FRAMERATE);
};
c.stop=function(){if(c.intervalID){clearInterval(c.intervalID);
}};
c.Mouse=new (function(){this.events=[];
this.hasEvents=function(){return this.events.length!=0;
};
this.onclick=function(e,f){this.events.push({type:"onclick",x:e,y:f,run:function(g){if(g.onclick){g.onclick();
}}});
};
this.onmousemove=function(e,f){this.events.push({type:"onmousemove",x:e,y:f,run:function(g){if(g.onmousemove){g.onmousemove();
}}});
};
this.eventElements=[];
this.checkPath=function(g,e){for(var f=0;
f<this.events.length;
f++){var h=this.events[f];
if(e.isPointInPath&&e.isPointInPath(h.x,h.y)){this.eventElements[f]=g;
}}};
this.checkBoundingBox=function(f,h){for(var e=0;
e<this.events.length;
e++){var g=this.events[e];
if(h.isPointInBox(g.x,g.y)){this.eventElements[e]=f;
}}};
this.runEvents=function(){c.ctx.canvas.style.cursor="";
for(var f=0;
f<this.events.length;
f++){var g=this.events[f];
var e=this.eventElements[f];
while(e){g.run(e);
e=e.parent;
}}this.events=[];
this.eventElements=[];
};
});
return c;
}})();
if(typeof(CanvasRenderingContext2D)!="undefined"){CanvasRenderingContext2D.prototype.drawSvg=function(b,e,d,a,c){canvg(this.canvas,b,{ignoreMouse:true,ignoreAnimation:true,ignoreDimensions:true,ignoreClear:true,offsetX:e,offsetY:d,scaleWidth:a,scaleHeight:c});
};
}