(function(q){var h=q.Chart,w=q.addEvent,z=q.removeEvent,i=q.createElement,b=q.discardElement,c=q.css,m=q.merge,u=q.each,x=q.extend,e=Math.max,n=document,a=window,H=q.isTouchDevice,d=q.Renderer.prototype.symbols,g=q.getOptions(),G;
x(g.lang,{printChart:"Print chart",downloadPNG:"Download PNG image",downloadJPEG:"Download JPEG image",downloadPDF:"Download PDF document",downloadSVG:"Download SVG vector image",contextButtonTitle:"Chart context menu"});
g.navigation={menuStyle:{border:"1px solid #A0A0A0",background:"#FFFFFF",padding:"5px 0"},menuItemStyle:{padding:"0 10px",background:"none",color:"#303030",fontSize:H?"14px":"11px"},menuItemHoverStyle:{background:"#4572A5",color:"#FFFFFF"},buttonOptions:{symbolFill:"#E0E0E0",symbolSize:14,symbolStroke:"#666",symbolStrokeWidth:3,symbolX:12.5,symbolY:10.5,align:"right",buttonSpacing:3,height:22,theme:{fill:"white",stroke:"none"},verticalAlign:"top",width:24}};
g.exporting={type:"image/png",url:"http://export.highcharts.com/",buttons:{contextButton:{menuClassName:"highcharts-contextmenu",symbol:"menu",_titleKey:"contextButtonTitle",menuItems:[{textKey:"printChart",onclick:function(){this.print();
}},{separator:!0},{textKey:"downloadPNG",onclick:function(){this.exportChart();
}},{textKey:"downloadJPEG",onclick:function(){this.exportChart({type:"image/jpeg"});
}},{textKey:"downloadPDF",onclick:function(){this.exportChart({type:"application/pdf"});
}},{textKey:"downloadSVG",onclick:function(){this.exportChart({type:"image/svg+xml"});
}}]}}};
q.post=function(f,j,k){var l,f=i("form",m({method:"post",action:f,enctype:"multipart/form-data"},k),{display:"none"},n.body);
for(l in j){i("input",{type:"hidden",name:l,value:j[l]},null,f);
}f.submit();
b(f);
};
x(h.prototype,{getSVG:function(f){var p=this,j,l,o,k,r=m(p.options,f);
if(!n.createElementNS){n.createElementNS=function(t,s){return n.createElement(s);
};
}f=i("div",null,{position:"absolute",top:"-9999em",width:p.chartWidth+"px",height:p.chartHeight+"px"},n.body);
l=p.renderTo.style.width;
k=p.renderTo.style.height;
l=r.exporting.sourceWidth||r.chart.width||/px$/.test(l)&&parseInt(l,10)||600;
k=r.exporting.sourceHeight||r.chart.height||/px$/.test(k)&&parseInt(k,10)||400;
x(r.chart,{animation:!1,renderTo:f,forExport:!0,width:l,height:k});
r.exporting.enabled=!1;
r.series=[];
u(p.series,function(s){o=m(s.options,{animation:!1,showCheckbox:!1,visible:s.visible});
o.isInternal||r.series.push(o);
});
j=new q.Chart(r,p.callback);
u(["xAxis","yAxis"],function(s){u(p[s],function(t,B){var v=j[s][B],A=t.getExtremes(),y=A.userMin,A=A.userMax;
v&&(y!==void 0||A!==void 0)&&v.setExtremes(y,A,!0,!1);
});
});
l=j.container.innerHTML;
r=null;
j.destroy();
b(f);
l=l.replace(/zIndex="[^"]+"/g,"").replace(/isShadow="[^"]+"/g,"").replace(/symbolName="[^"]+"/g,"").replace(/jQuery[0-9]+="[^"]+"/g,"").replace(/url\([^#]+#/g,"url(#").replace(/<svg /,'<svg xmlns:xlink="http://www.w3.org/1999/xlink" ').replace(/ href=/g," xlink:href=").replace(/\n/," ").replace(/<\/svg>.*?$/,"</svg>").replace(/&nbsp;/g,"Â ").replace(/&shy;/g,"Â").replace(/<IMG /g,"<image ").replace(/height=([^" ]+)/g,'height="$1"').replace(/width=([^" ]+)/g,'width="$1"').replace(/hc-svg-href="([^"]+)">/g,'xlink:href="$1"/>').replace(/id=([^" >]+)/g,'id="$1"').replace(/class=([^" >]+)/g,'class="$1"').replace(/ transform /g," ").replace(/:(path|rect)/g,"$1").replace(/style="([^"]+)"/g,function(s){return s.toLowerCase();
});
return l=l.replace(/(url\(#highcharts-[0-9]+)&quot;/g,"$1").replace(/&quot;/g,"'");
},exportChart:function(f,j){var f=f||{},k=this.options.exporting,k=this.getSVG(m({chart:{borderRadius:0}},k.chartOptions,j,{exporting:{sourceWidth:f.sourceWidth||k.sourceWidth,sourceHeight:f.sourceHeight||k.sourceHeight}})),f=m(this.options.exporting,f);
q.post(f.url,{filename:f.filename||"chart",type:f.type,width:f.width||0,scale:f.scale||2,svg:k},f.formAttributes);
},print:function(){var j=this,k=j.container,p=[],f=k.parentNode,o=n.body,l=o.childNodes;
if(!j.isPrinting){j.isPrinting=!0,u(l,function(s,r){if(s.nodeType===1){p[r]=s.style.display,s.style.display="none";
}}),o.appendChild(k),a.focus(),a.print(),setTimeout(function(){f.appendChild(k);
u(l,function(s,r){if(s.nodeType===1){s.style.display=p[r];
}});
j.isPrinting=!1;
},1000);
}},contextMenu:function(F,J,l,D,r,C,B){var y=this,A=y.options.navigation,I=A.menuItemStyle,p=y.chartWidth,k=y.chartHeight,s="cache-"+F,t=y[s],o=e(r,C),j,f,E,v=function(K){y.pointer.inClass(K.target,F)||f();
};
if(!t){y[s]=t=i("div",{className:F},{position:"absolute",zIndex:1000,padding:o+"px"},y.container),j=i("div",null,x({MozBoxShadow:"3px 3px 10px #888",WebkitBoxShadow:"3px 3px 10px #888",boxShadow:"3px 3px 10px #888"},A.menuStyle),t),f=function(){c(t,{display:"none"});
B&&B.setState(0);
y.openMenu=!1;
},w(t,"mouseleave",function(){E=setTimeout(f,500);
}),w(t,"mouseenter",function(){clearTimeout(E);
}),w(document,"mouseup",v),w(y,"destroy",function(){z(document,"mouseup",v);
}),u(J,function(L){if(L){var K=L.separator?i("hr",null,null,j):i("div",{onmouseover:function(){c(this,A.menuItemHoverStyle);
},onmouseout:function(){c(this,I);
},onclick:function(){f();
L.onclick.apply(y,arguments);
},innerHTML:L.text||y.options.lang[L.textKey]},x({cursor:"pointer"},I),j);
y.exportDivElements.push(K);
}}),y.exportDivElements.push(j,t),y.exportMenuWidth=t.offsetWidth,y.exportMenuHeight=t.offsetHeight;
}J={display:"block"};
l+y.exportMenuWidth>p?J.right=p-l-r-o+"px":J.left=l-o+"px";
D+C+y.exportMenuHeight>k&&B.alignOptions.verticalAlign!=="top"?J.bottom=k-D-o+"px":J.top=D+C-o+"px";
c(t,J);
y.openMenu=!0;
},addButton:function(s){var r=this,B=r.renderer,C=m(r.options.navigation.buttonOptions,s),v=C.onclick,f=C.menuItems,A,p,t={stroke:C.symbolStroke,fill:C.symbolFill},j=C.symbolSize||12;
if(!r.btnCount){r.btnCount=0;
}if(!r.exportDivElements){r.exportDivElements=[],r.exportSVGElements=[];
}if(C.enabled!==!1){var o=C.theme,l=o.states,k=l&&l.hover,l=l&&l.select,y;
delete o.states;
v?y=function(){v.apply(r,arguments);
}:f&&(y=function(){r.contextMenu(p.menuClassName,f,p.translateX,p.translateY,p.width,p.height,p);
p.setState(2);
});
C.text&&C.symbol?o.paddingLeft=q.pick(o.paddingLeft,25):C.text||x(o,{width:C.width,height:C.height,padding:0});
p=B.button(C.text,0,0,y,o,k,l).attr({title:r.options.lang[C._titleKey],"stroke-linecap":"round"});
p.menuClassName=s.menuClassName||"highcharts-menu-"+r.btnCount++;
C.symbol&&(A=B.symbol(C.symbol,C.symbolX-j/2,C.symbolY-j/2,j,j).attr(x(t,{"stroke-width":C.symbolStrokeWidth||1,zIndex:1})).add(p));
p.add().align(x(C,{width:p.width,x:q.pick(C.x,G)}),!0,"spacingBox");
G+=(p.width+C.buttonSpacing)*(C.align==="right"?-1:1);
r.exportSVGElements.push(p,A);
}},destroyExport:function(f){var f=f.target,j,k;
for(j=0;
j<f.exportSVGElements.length;
j++){if(k=f.exportSVGElements[j]){k.onclick=k.ontouchstart=null,f.exportSVGElements[j]=k.destroy();
}}for(j=0;
j<f.exportDivElements.length;
j++){k=f.exportDivElements[j],z(k,"mouseleave"),f.exportDivElements[j]=k.onmouseout=k.onmouseover=k.ontouchstart=k.onclick=null,b(k);
}}});
d.menu=function(f,j,k,l){return["M",f,j+2.5,"L",f+k,j+2.5,"M",f,j+l/2+0.5,"L",f+k,j+l/2+0.5,"M",f,j+l-1.5,"L",f+k,j+l-1.5];
};
h.prototype.callbacks.push(function(f){var j,k=f.options.exporting,l=k.buttons;
G=0;
if(k.enabled!==!1){for(j in l){f.addButton(l[j]);
}w(f,"destroy",f.destroyExport);
}});
})(Highcharts);