(function(c){var i=c.getOptions(),e=i.plotOptions,g=c.seriesTypes,f=c.merge,h=function(){},a=c.each;
e.funnel=f(e.pie,{animation:!1,center:["50%","50%"],width:"90%",neckWidth:"30%",height:"100%",neckHeight:"25%",reversed:!1,dataLabels:{connectorWidth:1,connectorColor:"#606060"},size:!0,states:{select:{color:"#C0C0C0",borderColor:"#000000",shadow:!1}}});
g.funnel=c.extendClass(g.pie,{type:"funnel",animate:h,singularTooltips:!0,translate:function(){var k=function(o,p){return/%$/.test(o)?p*parseInt(o,10)/100:parseInt(o,10);
},P=0,J=this.chart,M=this.options,G=M.reversed,d=J.plotWidth,U=J.plotHeight,E=0,J=M.center,n=k(J[0],d),I=k(J[0],U),S=k(M.width,d),V,Q,A=k(M.height,U),O=k(M.neckWidth,d),L=k(M.neckHeight,U),K=A-L,k=this.data,F,D,R=M.dataLabels.position==="left"?1:0,m,T,N,b,l,H,j;
this.getWidthAt=Q=function(o){return o>A-L||A===L?O:O+(S-O)*((A-L-o)/(A-L));
};
this.getX=function(o,p){return n+(p?-1:1)*(Q(G?U-o:o)/2+M.dataLabels.distance);
};
this.center=[n,I,A];
this.centerX=n;
a(k,function(o){P+=o.y;
});
a(k,function(o){j=null;
D=P?o.y/P:0;
T=I-A/2+E*A;
l=T+D*A;
V=Q(T);
m=n-V/2;
N=m+V;
V=Q(l);
b=n-V/2;
H=b+V;
T>K?(m=b=n-O/2,N=H=n+O/2):l>K&&(j=l,V=Q(K),b=n-V/2,H=b+V,l=K);
G&&(T=A-T,l=A-l,j=j?A-j:null);
F=["M",m,T,"L",N,T,H,l];
j&&F.push(H,j,b,j);
F.push(b,l,"Z");
o.shapeType="path";
o.shapeArgs={d:F};
o.percentage=D*100;
o.plotX=n;
o.plotY=(T+(j||l))/2;
o.tooltipPos=[n,o.plotY];
o.slice=h;
o.half=R;
E+=D;
});
},drawPoints:function(){var j=this,d=j.options,b=j.chart.renderer;
a(j.data,function(l){var m=l.graphic,k=l.shapeArgs;
m?m.animate(k):l.graphic=b.path(k).attr({fill:l.color,stroke:d.borderColor,"stroke-width":d.borderWidth}).add(j.group);
});
},sortByAngle:function(b){b.sort(function(j,d){return j.plotY-d.plotY;
});
},drawDataLabels:function(){var m=this.data,l=this.options.dataLabels.distance,k,j,p,d=m.length,b,n;
for(this.center[2]-=2*l;
d--;
){p=m[d],j=(k=p.half)?1:-1,n=p.plotY,b=this.getX(n,k),p.labelPos=[0,n,b+(l-5)*j,n,b+l*j,n,k?"right":"left",0];
}g.pie.prototype.drawDataLabels.call(this);
}});
i.plotOptions.pyramid=c.merge(i.plotOptions.funnel,{neckWidth:"0%",neckHeight:"0%",reversed:!0});
c.seriesTypes.pyramid=c.extendClass(c.seriesTypes.funnel,{type:"pyramid"});
})(Highcharts);